- name: Change dns
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: '0644'
    owner: root
    group: root
    backup: yes

- name: Install dependencies
  apt:
    name: "apt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common"
    state: latest 
    update_cache: yes

- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: "docker-ce,docker-ce-cli,containerd.io"
    state: latest
    update_cache: yes
  environment:
    RUNLEVEL: 1


- name: create docker unit dir
  with_items:
    - docker.service.d
    - containerd.service.d
  file:
    path: "/etc/systemd/system/{{item}}/"
    state: directory
  tags: ["tune-only"]


- name: Tune Docker
  with_items:
    - docker.service.d
    - containerd.service.d
  template:
    src: override.conf.j2
    dest: "/etc/systemd/system/{{item}}/override.conf"
    mode: '0644'
    owner: root
    group: root
    backup: yes
  tags: ["tune-only"]

- name: Start Docker
  with_items:
    - containerd
    - docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{item}}"
  tags: ["tune-only","restart-only"]
