- name: Change dns
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: '0644'
    owner: root
    group: root
    backup: yes

- name: Install dependencies
  apt:
    name: "apt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common"
    state: latest 
    update_cache: yes

- name: Add kubeadm gpg key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 

- name: Add kubernetes repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main 
    state: present
    update_cache: yes

- name: Install Kubeadm,Kubelet,Kubectl
  apt:
    name: "kubelet,kubeadm,kubectl"
    state: latest
    update_cache: yes

- name: Get kubeadm images
  shell: kubeadm config images pull
